### ISSUE TITLE
allow bind is not honoured

### ISSUE THREAD

**Issue by magwas** [edemo/wp_oauth_plugin#88]
======================================================================
FAIL: test_install_page (InstallTest.InstalltestTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/wp_oauth_plugin/end2endtest/InstallTest.py", line 32, in test_install_page
    self.assertSelected("EdemoSSO_allowBind")
  File "/wp_oauth_plugin/end2endtest/InstallTest.py", line 22, in assertSelected
    self.assertEqual(True,element.is_selected())
AssertionError: True != False

----------------------------------------------------------------------
Ran 1 test in 58.893s

commiting test later

test is in ac404a6d480581951b8c70148a403123c1e1861a magwas/develop.

Will comment out the relevant test in later commits until a fix is delivered.

**Comment by magwas** [comment]
sorry, false report.
